### ISSUE TITLE
Support source maps

### ISSUE THREAD

**Issue by Razican** [compass-rs/sass-rs#59]
Hi!
When developing, having source maps is a really nice feature to have, and as far as I know, libsass has built-in source-map support. Would it be possible to have this feature in sass-rs?

I would be happy to help with the implementation if I'm given some pointers, I don't know much about the C API (or where to find nice documentation about it).

**Comment by Keats** [comment]
Hi

I am not going to implement sourcemaps myself but would welcome a PR.

I'm not entirely sure either for the C API documentation to be honest, it's probably just a config option to pass when rendering. You can have a look at [node-sass](https://github.com/sass/node-sass) to see how they are doing it since it's written by the same people as libsass afaik.
