### ISSUE TITLE
Getting list of imports?

### ISSUE THREAD

**Issue by kaj** [compass-rs/sass-rs#6]
Is there a way to get a list (`Vec<Path>`) of `@import`-ed files?  There doesn't seem to be an obvious and easy way, but maybe by creating a `SassImporter`?

**Comment by cipriancraciun** [comment]
Is there a technical limitation why this is not (yet) possible?

----

I don't know how others are using `sass-rs`, but I intend to use it from `build.rs`, thus integrate the CSS build into the `cargo` build of the project.

However, if one uses this from `build.rs`, then it is essential to know what other files were imported, so one can report the proper dependencies to `cargo`, else a recompile wouldn't be triggered if an imported file changes.

**Comment by Keats** [comment]
It might be possible to get it by adding some more bindings to libsass but this crate is not maintained anymore as Libsass is deprecated.

I recommend using https://github.com/kaj/rsass or https://github.com/connorskees/grass instead.

**Comment by cipriancraciun** [comment]
@Keats I know that `libsass` is being deprecated (which is sad, but such is life), however neither `rsass` nor `grass` is yet compliant with `libsass`, and given that many development tools rely on the "standard SASS", it would not be straight forward.

Moreover, even `libsass` has its quirks, and I don't want to re-learn the quirks of each new SASS re-implementation.  :)

(Also, I don't remember which of `rsass` or `grass`, but one of them also misses this feature...)

**Comment by Keats** [comment]
> neither rsass nor grass is yet compliant with libsass, and given that many development tools rely on the "standard SASS"

**Comment by cipriancraciun** [comment]
> > neither rsass nor grass is yet compliant with libsass, and given that many development tools rely on the "standard SASS"
> 
> Just to add some details, [...]

Well I'm quoting what the authors of `rsass` and `grass` are saying:

=> <https://github.com/kaj/rsass>:
> The sass language is defined in its reference doc. This implementation is incomplete but getting there, if slowly.
> Progress: 4013 of 6478 tests passed in dart-sass compatibility mode.

BTW, the developers of `rsass` are pointing to `sass-rs`:  :)
> If you want a working rust library for sass right now, you may be better of with [sass-rs](https://crates.io/crates/sass-rs) or [sass-alt](https://crates.io/crates/sass-alt), which are rust wrappers around libsass.

=> <https://github.com/connorskees/grass>:
> grass has reached a stage where one can be quite confident in its output. For the average user there should not be perceptible differences from dart-sass. [...]
> grass is not a drop-in replacement for libsass and does not intend to be. If you are upgrading to grass from libsass, you may have to make modifications to your stylesheets, though these changes should not differ from those you would have to make if upgrading to dart-sass.

So, basically neither of them is a drop-in-replacement to `libsass`.

----

> [...] the standard SASS is dart-sass and I don't think libsass is compliant with that either

My point is this:  if one relies on `sassc` / `libsass` (i.e. the C implementation) for CSS, especially since it works without having Ruby / Dart or other complex environments, then in Rust there doesn't seem to be a good replacement, especially when wanting to integrate it in `build.rs`.

For example, I'm not a web developer, however I do write CSS.  Most of the times I write plain CSS, but some times I want / need SASS to solve some repetitions.  I've learned enough SASS to get going, and it works great.  Thus I see no point in "upgrading" to a newer version of SASS, given that my needs are basic, and that the "better" version is more complex to be used.

My opinion is that `libsass` is "good-enough" as it is, and it's not a moving target, thus it can be relied upon.  I've already learned all its quirks, like [this one](https://github.com/sass/libsass/issues/3108) for example, thus I'm at that point where I'm just "productive" with it.

**Comment by Keats** [comment]
It kinda depends on the perspective for the maturity. Sass is getting lots of new features which aren't supported in libsass. The sass-spec is not the graal either, running it on libsass main gives me `6567 runs, 133 passing, 6433 failures,`, and yet many people including us are using it well ;)

Anyway, if you're productive with it (like me as well, I don't use any of the new features so far) no reason to change. At the same time no more features will be added to this crate.

As for your watching issue, would files be contained in a single folder or they can be anywhere? If you can restrict to a single folder then you can just watch changes in there and rebuild the whole thing.

**Comment by cipriancraciun** [comment]
> As for your watching issue, would files be contained in a single folder or they can be anywhere? If you can restrict to a single folder then you can just watch changes in there and rebuild the whole thing.

The problem is not watching with a tool like `watchexec`, the problem is `cargo`'s `bulid.rs` dependency mechanism (as per <https://doc.rust-lang.org/cargo/reference/build-scripts.html>), `cargo` expects that `build.rs` to output one of the following:
* `cargo:rerun-if-changed=PATH`, where `PATH` is a file -- thus one for each of the dependent SASS files;  (**what I'm trying to achieve;**)
* `cargo:rerun-if-changed=PATH`, where `PATH` is a folder -- thus it can be the root of the SASS source tree;  however, if one uses a folder, then `cargo` will insist on rebuilding the code if **any** file changes underneath;  (and given the rust rebuild times it's not very pleasant...)

But my main issue is this: I am writing a generic semi-static web-server in Rust, and thus I don't exactly know where the user has decided to place his SASS sources.  Thus either I am able to track them, or to ask the user to give "watch-for" folders;  I would prefer the former as it's less of a hassle for the developer.  Here is an example:
<https://github.com/console9/hyper-static-server/blob/master/examples/sources/routes.in#L52-L54>

----

> At the same time no more features will be added to this crate.

I kind of understand this.

However, given how useful such a use-case might be, see for example this issue in `grass` <https://github.com/connorskees/grass/issues/46>, which only recently implemented it, one could perhaps make an exception?  :)

I've tried implementing this myself on-top of `sass-alt`:
<https://github.com/console9/hyper-static-server/blob/dfe5427bccaa4e701e1dd31cbe8b1e959c762d5a/sources/support_sass.rs#L67-L112>

However for some reason it panics, and I've failed to properly implement it.

But, given that you've also implemented the `sass-sys` crate, you are well aware of the source code, and perhaps could easily implement such a feature.

In the end in doesn't even have to be as complex as "callback import resolution", just as simple as "here is a list of files we have loaded during the compilation".

----

It seems that `libsass` already has support for this, as per:
<https://github.com/sass/libsass/blob/288610acfaa797b44c1a58a18b2cbd2e03937498/src/sass_context.hpp#L96>

And `sass-sys` already exports this as:
<https://docs.rs/sass-sys/0.4.22/sass_sys/fn.sass_context_get_included_files.html>

Thus my assumption is that a simple addition to the Rust code would solve this.
