### ISSUE TITLE
Building for Windows on GitHub Actions

### ISSUE THREAD

**Issue by littledivy** [compass-rs/sass-rs#73]
Hey there! Great work, I'm maintaining [deno-sass](https://github.com/divy-work/deno-sass) which binds sass-rs to the Deno runtime. 

I've been producing builds for the same using GitHub actions on Ubuntu and Mac but builds always fail on the windows CI.

One of the runs that fail:
https://github.com/divy-work/deno-sass/runs/790379513?check_suite_focus=true

The action workflow file:
https://github.com/divy-work/deno-sass/blob/master/.github/workflows/main.yml

Thanks

**Comment by Keats** [comment]
Building on Windows is very finnicky, I only got it working after a lot of trial and errors. I'm kind of hoping https://github.com/connorskees/grass will make this repository obsolete.

**Comment by ta32** [comment]
@Keats I was trying to install trunk and this crate is a dependency on windows 
I built with a VS 2019 shell, however i get this error 
 thread 'main' panicked at 'Failed to run make/gmake.
Why is it trying to use make?

Is it because my active tool chain is?
active toolchain
----------------
stable-x86_64-pc-windows-gnu (default)
